on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2-beta
      with:
        # Private version of https://github.com/actions/hello-world-docker-action
        repository: qejk/private-hello-world-docker-action
    - name: Run the private action
      uses: ./
      with:
        who-to-greet: "Mona the Octocat"